name: JAMYSystem
version: '${project.version}'
main: jamy.jamysystem.JAMYSystem
api-version: 1.19
commands:
  test:
    description: test
  JAMYShop:
    description: JAMYShop
    aliases: shop
    usage: |
      /shop <name>
          open // 상점을 엽니다 
          register <price:int> <stock:boolean> <howMany:int::default=0>
          getregister <price:int> 
