name: JAMYSystem
version: '${project.version}'
main: jamy.jamysystem.JAMYSystem
api-version: 1.19
commands:
  yamltest:
    description: yamltest
  JAMYShop:
    description: JAMYShop
    aliases: shop
    usage: /shop open [<String>] // 상점을 엽니다
    /shop delete [<String>] // 상점을 삭제합니다
