name: JAMYSystem
version: '${project.version}'
main: jamy.jamysystem.JAMYSystem
api-version: 1.19
commands:
  test:
    description: test
  JAMYShop:
    description: JAMYShop
    aliases: shop
    usage: /shop open [<String>] // 상점을 엽니다
